apiVersion: v1
kind: Pod
metadata:
  name: squid
  labels:
    name: squid
spec:
  containers:
    - name: squid
      image: quay.io/janeuner/squid:4.10-1
      ports:
        - containerPort: 3128
          protocol: TCP
      volumeMounts:
        - mountPath: /var/spool/squid
          name: data
  volumes:
    - name: data
      emptyDir: {}
